2021-02-02 18:06:52,585 INFO    MainThread:803 [wandb_setup.py:_flush():70] setting env: {}
2021-02-02 18:06:52,586 INFO    MainThread:803 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-02 18:06:52,586 INFO    MainThread:803 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-02 18:06:52,586 INFO    MainThread:803 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9dbccff390>
2021-02-02 18:06:52,587 INFO    MainThread:803 [wandb_init.py:_log_setup():318] Logging user logs to /content/instance-video-colorization/wandb/run-20210202_180652-1uirhcg1/logs/debug.log
2021-02-02 18:06:52,587 INFO    MainThread:803 [wandb_init.py:_log_setup():319] Logging internal logs to /content/instance-video-colorization/wandb/run-20210202_180652-1uirhcg1/logs/debug-internal.log
2021-02-02 18:06:55,054 INFO    MainThread:803 [wandb_run.py:_console_start():1399] atexit reg
2021-02-02 18:06:55,054 INFO    MainThread:803 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.WRAP
2021-02-02 18:06:55,056 INFO    MainThread:803 [wandb_run.py:_redirect():1297] Wrapping output streams.
2021-02-02 18:06:55,056 INFO    MainThread:803 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-02 18:06:55,062 INFO    MainThread:803 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 18:06:55,072 INFO    MainThread:803 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 18:06:55,077 INFO    MainThread:803 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 18:06:55,081 INFO    MainThread:803 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 18:06:55,280 INFO    MainThread:803 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 18:06:55,292 INFO    MainThread:803 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 18:07:01,012 INFO    MainThread:803 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 18:07:23,208 INFO    MainThread:803 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 0
2021-02-02 18:07:23,209 INFO    MainThread:803 [wandb_run.py:_restore():1341] restore
2021-02-02 18:07:23,431 INFO    MainThread:803 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 868
  total_bytes: 868
}

2021-02-02 18:07:25,441 INFO    MainThread:803 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9020
  total_bytes: 9020
}

2021-02-02 18:07:26,739 INFO    MainThread:803 [wandb_run.py:_show_files():1714] logging synced files
2021-02-02 18:07:26,743 INFO    MainThread:803 [internal.py:handle_exit():156] Internal process exited
